### ISSUE TITLE
Duplicate Sentance

### ISSUE THREAD

**Issue by troyredder** [tiagomnh/LicensingViewController#6]
The phrase "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," for MIT licenses is repeated within private let mitFormat in License.swift.

**Comment by tiagomnh** [comment]
Nice catch! 🎣 

Removed the duplicate text just now. Thanks for letting me know. 👍
